### ISSUE TITLE
Is there a full SDK like there is for your professional cards?

### ISSUE THREAD

**Issue by rlewkowicz** [AVerMedia-Technologies-Inc/CreatorCentralSDK#2]
@avermediachiwenlin 
@AVerMediaJimmyHu 

Is there a full SDK for your consumer cards like there is for your professional ones? I would have bought a frame grabber or even the professional cards had I known there was no integration. 

I very much would like an sdk similar to AVerMedia Capture Card Software Development Kit

**Comment by AVerMediaJimmyHu** [comment]
Thank you for your interest in an SDK for our consumer cards! Currently all of our consumer cards are standard UVC devices. This means that they can be used with a wide variety of software applications without the need for any special drivers or SDKs. This offers flexibility without a full SDK.

While I'm unable to provide direct assistance with this product line, I can certainly help you connect with the appropriate team. Can you tell me more about the specific functionalities you're hoping to achieve with your project? This will help them understand your needs better and suggest potential solutions.

**Comment by rlewkowicz** [comment]
@AVerMediaJimmyHu i have the live streamer 4k. The sdk kit doesn't enumerate it I don't think. 

None of the samples pick it up, but Rec central does. 

I want to grab frames off the buffer as they arrive using c++

**Comment by rlewkowicz** [comment]
I reached out through some portal and I guess its not supported. I wish the docs and site made this more clear with a compatibility matrix. I bought it just for this project I'm working on. 

Functionally the consumer cards seem more performant, is there even a professional grade 2.1 card (not that mine is 2.1)? 

I hope you would consider supporting the card with some sort of sdk. I'll look at the OBS integrations and see if I can't hack something up there.

**Comment by rlewkowicz** [comment]
I don't like the obs stuff because its custom. 

https://github.com/obsproject/libdshowcapture/blob/master/source/device-vendor.cpp

Its gross. It's all just hardcoded lol. I don't wanna use any of this but I can if I have to.

I'm trying https://learn.microsoft.com/en-us/uwp/api/windows.media.capture?view=winrt-22621

I'm having a heck of a time enumerating and dumping device info. It seems video and capture code all died ~10 years ago. Even your sdk is all old. The windows examples are all old and it doesn't help the whole winrt uwp ecosystem is an absolute nightmare. 

I've found a video source on my PC, but I can't figure out what it is. I'm about to pull the card out and see if it still pops up but that's so goofy.

**Comment by rlewkowicz** [comment]
I pulled the card and I'm getting a single id still in windows media capture. 

This is absolutely nuts. I don't know if everyone just got their stock grants and dipped, but this entire space died 10 years ago almost on the nose. 

Even VLC and all that. It's a method called directshow. I imagine the libdshow is an extension of this.

**Comment by AVerMediaJimmyHu** [comment]
@rlewkowicz I apologize for the delay in getting back to you. We were working on Computex 2024 last few days.

I understand that you've been experiencing some challenges with Windows Media Capture APIs. We've encountered similar issues in using Windows Audio Session API as well. They can't complete everything we need in implementations. In some cases, we've had to use DirectShow to get the desired results.

I also received an update from our project management team. They are eager to learn more about your project requirements and explore potential collaboration opportunities. However, I couldn't find your email address in public records. Could you leave your contact information [in our website](https://www.avermedia.com/professional/support/contact) (https://www.avermedia.com/professional/support/contact) so that our project management team can reach out to you? They plan to reach out to you via email in private to discuss this further.

**Comment by AVerMediaJimmyHu** [comment]
Close it since it is redirected.
